name: "Hello, world!"

on: [push]

jobs:

  build: # there should be a diagnostic here about missing timeout-minutes
    name: Greeting
    runs-on: ubuntu-latest
    
    steps:
      - name: Hello world
        uses: Brightspace/third-party-actions@actions/hello-world-javascript-action
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello

      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
